### ISSUE TITLE
Document keys are partially hidden.

### ISSUE THREAD

**Issue by dropocol** [mongodb-js/compass#2946] opened 2022-04-05 12:52 UTC
#### Current Behavior

The keys are not fully visible and show dots instead.
![image](https://user-images.githubusercontent.com/11982876/161756818-1c3f03b8-072f-4b51-8fc1-a4d715d52a5c.png)

I have tried reinstalling but it's still the same. Zoom-in, Zoom-out doesn't work either.

**Comment by addaleax** [comment] 2022-04-05 13:08
Hi @dropocol!

This seems a lot like https://jira.mongodb.org/browse/COMPASS-5361, which was fixed in Compass 1.31.0. I’d recommend you double-check:
- That you are using the latest version of Compass
- That the field names are not *actually* stored with ellipses in the database, e.g. by cross-referencing with a shell (mongosh) query or by running schema analysis in Compass.

**Comment by dropocol** [comment] 2022-04-05 17:20
Hi @addaleax , Thanks for the update. 

I am currently on 1.31.1 so it's the latest version. Also checked the data in mongosh and it looks fine. Any other suggestion to solve this issue?

<img width="461" alt="image" src="https://user-images.githubusercontent.com/11982876/161813791-e5b4caba-79ca-4509-af98-43076a7a410e.png">

**Comment by Anemy** [comment] 2022-04-05 19:16
Hi @dropocol , I haven't been able to reproduce with similar data,
![Screen Shot 2022-04-05 at 3 05 48 PM](https://user-images.githubusercontent.com/1791149/161831943-f012458d-fa72-4840-bac4-c1ab392a76ff.png)
![Screen Shot 2022-04-05 at 3 09 27 PM](https://user-images.githubusercontent.com/1791149/161831944-752e3b7a-dc9b-4cd9-997e-59b2b9bbf6d5.png)
Which OS are you using Compass on? Are you using a custom desktop font?

**Comment by dropocol** [comment] 2022-04-05 19:17
A temporary solution that I've found

1. Open the Dev Tools by pressing `option + cmd + I` or go to `view -> Toggle DevTools`
2. Click on any of the arrow icon in the image below.
![image](https://user-images.githubusercontent.com/11982876/161831826-43cf43e3-5173-4c82-af99-1325552f7992.png)

3. Select any of the element that has a hidden data on it.
4. It will have a class similar to `leafygreen-ui-15lrq0l`
5. On the right side panel, you will see the properties of the css class. 
![image](https://user-images.githubusercontent.com/11982876/161832159-15fae684-7e12-4ddf-85bb-e33e47286713.png)

6. Uncheck the `overflow-x : hidden` and you are good to go.

**Comment by dropocol** [comment] 2022-04-05 19:20
Hi @Anemy , I am on MacOS Monterey 12.1. The compass version that I have installed is 1.31.1 and I am not using any custom fonts.
![image](https://user-images.githubusercontent.com/11982876/161832950-cc5e2e2b-d309-44a7-abac-b6ef9b73bee2.png)

**Comment by dropocol** [comment] 2022-08-31 02:23
Any update on this issue? I've been using the temporary hack for a few months now but would love to see this issue resolved. Thank you.

**Comment by Anemy** [comment] 2022-09-07 16:33
@dropocol We're not sure what's causing this issue, we have yet to see other folks impacted by it. Do you have any other any configurations on your computer that impact electron/chromium based applications? If you uninstall Compass and reinstall it does the issue persist? Let us know if there's any other information that might help us diagnose or reproduce the issue.

**Comment by dropocol** [comment] 2022-09-07 17:20
I've reinstalled it a couple of times and it always shows up. I really don't understand what else I can do to make it go away as it's too annoying. I always have to use the dev tools to disable the css class to make it work.

All other electron/chromium based apps work fine on my computer and no other app shows any kind of issues. It's only Compass.

**Closed** 2022-12-03 14:56 UTC

**Comment by Anemy** [comment] 2022-12-03 16:46
@dropocol did it start working? Any insights in case this shows up again? We've updated some of our document rendering fairly recently so an update might solve some issues. Sorry we couldn't get to the cause of it.

**Comment by dropocol** [comment] 2022-12-03 18:44
@Anemy Yes. I've downloaded the new version and it's working fine now. The new UI looks awesome and is very responsive.
