### ISSUE TITLE
Bug Report: Loading connections not working properly

### ISSUE THREAD

**Issue by muhfaris** [mongodb-js/compass#3949] opened 2023-01-09 04:05 UTC
#### Current Behavior

The **Saved Connections** and **Recents** do not work properly.

Every makes a new connection and then adds into save the connection. It does not appear in the **Saved Connections** menu.

#### Expected Behavior/Code

The **Saved connections** menu can open and list all connections saved.

#### Environment

- node.js / npm versions: v18.12.1
- OS: Fedora (Linux fedora 6.0.15-300.fc37.x86_64)

#### Additional Context/Screenshots

![image](https://user-images.githubusercontent.com/16787866/211238730-350ac1fd-0ee2-4165-bb74-4f3141dbe14b.png)

**Comment by Anemy** [comment] 2023-01-09 20:54
Hi @muhfaris - I don't think those errors in the console are related to the connections not properly loading.
If possible can you share your Compass logs with us? It will likely log an error when loading connections which may give us more information. Be sure to redact any sensitive information. You can find the log in the `Help` menu then with the `Open Log File` option.

Which operating system are you using? I'm thinking the issue might be that you need to give Compass access to the keychain. If you don't have a keychain on your machine and you're on ubuntu you can look into installing one like `gnome-keyring`.

**Comment by muhfaris** [comment] 2023-01-10 04:39
hi @Anemy , thank for reply.

this log from starting the mongo compass until saving the connection.
[compass_63bcea084d3ce33f93a04654_log.txt](https://github.com/mongodb-js/compass/files/10378920/compass_63bcea084d3ce33f93a04654_log.txt)

**Comment by Anemy** [comment] 2023-01-10 14:25
@muhfaris hmmm not seeing anything telling in the logs, thanks for linking them. We'll have to double check our error catching around loading connections, I would have suspected it to show up there.
Do you have a credential store on your machine like `gnome-keyring` that Compass has access to? Although I don't know the exact failure that's happening I suspect it's related to that.

**Comment by muhfaris** [comment] 2023-01-11 16:53
default from fedora 37 has `A KDE wallet`, I think it is like a `gnome-keyring`.

**Comment by Anemy** [comment] 2023-06-01 10:46
Going to close this as a duplicate of https://github.com/mongodb-js/compass/issues/1911
Feel free to reopen if you feel it's a separate issue.
I'm thinking if we can't fix it we should at least document it and show something on Compass startup for folks.

**Closed by Anemy** 2023-06-01 10:46 UTC
