### ISSUE TITLE
Unset not working in Aggregations tab

### ISSUE THREAD

**Issue by thiagodsantos** [mongodb-js/compass#1923] opened 2020-03-18 18:59 UTC
Compass version: 1.20.5
OS: Windows Pro

Add stage $unset with a single field:
![error-mongodbcompass](https://user-images.githubusercontent.com/24657143/76996990-46c74580-6931-11ea-83d2-b7f1dd695210.PNG)

I tried in my API to test if the field is removed, and $unset works.

**Comment by Anemy** [comment] 2020-09-29 12:18
Hi @thiagodsantos I'm unable to reproduce this with the current Compass:
<img width="620" alt="Screen Shot 2020-09-29 at 2 15 04 PM" src="https://user-images.githubusercontent.com/1791149/94556921-2c661100-025e-11eb-9be3-36c4f8da9ec8.png">
I'm going to close this if that's alright - can you confirm if the issue has gone away? Feel free to reopen if not.

It doesn't look like this is the issue in your case, but it's possible sometimes to copy in quotes from a text editor which aren't valid quotes - curly quote characters: `“` vs `"` are invalid characters.

**Closed by Anemy** 2020-09-29 12:18 UTC
