### ISSUE TITLE
connect EHOSTUNREACH after upgrade to 1.27.0

### ISSUE THREAD

**Issue by ZhangPuXi** [mongodb-js/compass#2313] opened 2021-07-02 08:31 UTC
#### Current Behavior

connect EHOSTUNREACH after upgrade to 1.27.0. And then I downgrade to 1.25.0. All things worked well!

#### Environment

- OS: OSX 11.2.3

#### Additional Context/Screenshots

Broken in 1.27.0

<img width="833" alt="1 27 0" src="https://user-images.githubusercontent.com/15119639/124245746-da3a7f00-db52-11eb-960f-f80c6b4da8ee.png">

Worked well in 1.25.0

<img width="1498" alt="1 25 0" src="https://user-images.githubusercontent.com/15119639/124245821-ee7e7c00-db52-11eb-98d1-aa17b17c3efc.png">

**Comment by ZhangPuXi** [comment] 2021-07-02 08:49
<img width="1265" alt="1 26 1" src="https://user-images.githubusercontent.com/15119639/124248458-749bc200-db55-11eb-91bc-0c252471ea3f.png">
Also tried 1.26.1 and it works well!

**Comment by ZhangPuXi** [comment] 2021-07-02 09:06
114.116.235.191 is a public ip address and I do a haproxy to forward the requests to mongodb server(192.168.110.150)

**Comment by thmsl** [comment] 2021-07-02 09:48
I also received an error after upgrading to 1.27.0
`getaddrinfo ENOTFOUND` 

Environment: OS: OSX 11.4
Compass version: 1.26.0 to 1.27.0

Rolled back to 1.26.0 and issue is fixed.

**Comment by gribnoysup** [comment] 2021-07-02 09:49
Hey @thmsl, can you share more information about your connection options?

**Comment by gribnoysup** [comment] 2021-07-02 09:52
Also if possible, can you try connecting to the same server using [`mongosh`](https://docs.mongodb.com/mongodb-shell/)? Do you get the same error?

**Comment by thmsl** [comment] 2021-07-02 09:56
We use a port forward tunnel

![Screen Shot 2021-07-02 at 4 51 58 PM](https://user-images.githubusercontent.com/496215/124257113-3bb01d00-db56-11eb-82dd-2aa42fbcd5a5.png)

I'll try with `mongosh`

**Comment by thmsl** [comment] 2021-07-02 10:11
Mongosh 0.15.4 using same connection string works

```
Connecting to:		mongodb://<credentials>@127.0.0.1:27019/<redacted>?authSource=<redacted>&readPreference=primary&authMechanism=SCRAM-SHA-1&appname=MongoDB+Compass&ssl=false&directConnection=true&serverSelectionTimeoutMS=2000
Using MongoDB:		4.2.14
Using Mongosh Beta:	0.15.4
```

**Comment by gribnoysup** [comment] 2021-07-02 11:59
Thanks for trying it out! I think this confirms our suspicion of what's causing it, the fix is on its way in #2314. In the meantime you can try using the builds produced by CI in this PR (scroll to the bottom to see artifacts), this hopefully should resolve the issue: https://github.com/mongodb-js/compass/actions/runs/993292805

**Comment by Anemy** [comment] 2021-07-02 17:04
Hi @ZhangPuXi - we've just release[ 1.27.1 ](https://github.com/mongodb-js/compass/releases/tag/v1.27.1)which should have a fix for this connectivity issue, if you have a moment can you install it and see if the issue is solved? Thanks! And sorry for the inconvenience. 

https://github.com/mongodb-js/compass/releases/tag/v1.27.1

**Comment by ZhangPuXi** [comment] 2021-07-02 17:22
Hi @Anemy - I've tried 1.27.1 and it works. Thanks for your awesome works! Thanks very much, have a good day.

**Closed** 2021-07-02 17:33 UTC
