### ISSUE TITLE
Bug Report - execute exe from unexpected path

### ISSUE THREAD

**Issue by houjingyi233** [mongodb-js/compass#2066] opened 2020-11-23 07:37 UTC
#### Current Behavior

After install mongodb-compass-1.23.0-win32-x64.msi if you rename any exe to wmic.exe and put it to C:\node_modules\\.bin\wmic.exe then launch mongodb compass you can find C:\node_modules\\.bin\wmic.exe will be executed by mongodb compass.
As far as I know, this is because mongodb compass used NPM library execa(https://github.com/sindresorhus/execa) for process execution. When you set "preferLocal" to true in this library "C:\node_modules\\.bin" will be added to environment path. So if there is a "C:\node_modules\\.bin\wmic.exe" then it will be execute by mongodb compass. 

#### Expected Behavior/Code

C:\node_modules\\.bin\wmic.exe should not be executed by mongodb compass.

#### Environment

- OS: windows 10

#### Possible Solution

Set "preferLocal" to false should solve this.

#### Additional Context/Screenshots

I attached a stack trace in Process Monitor.

![stack-trace](https://user-images.githubusercontent.com/20239840/99937739-5f7dda00-2da1-11eb-98ce-0167fa8f1c5c.png)

**Comment by Anemy** [comment] 2020-12-14 16:08
Hi @houjingyi233  - thanks for reporting. This does look like a bug.
We're tracking this here in jira: https://jira.mongodb.org/browse/COMPASS-4510?filter=-2

**Comment by Anemy** [comment] 2020-12-15 02:04
Closing this as duplicate of https://github.com/mongodb-js/compass/issues/2061

**Closed by Anemy** 2020-12-15 02:04 UTC
