### ISSUE TITLE
_id Type being changed to int32 after editing via json if it was initially inserted as int64

### ISSUE THREAD

**Issue by abdudsoul** [mongodb-js/compass#2960] opened 2022-04-07 00:01 UTC
Only since the latest GUI Update: When you edit the document via json editor, if the _id field type was int64, changing any field in the Json View Editor will cause the _id field type to change to int32.

When viewing the document via JSON Viewer the int64 _id field is being represented like:
{
"_id": 3
}

however in the previous version you could specify that it is int64 with this:
{
"_id": {
          "$numberLong": "3"
     }
}

if you try to specify it with $numberLong in the latest compass it will just give you error that it is not possible to edit an immutable field _id.

#### Environment

- compass version: 1.31.1
- OS: Windows 10

#### Possible Solution

Works fine in previous version that does not have the latest UI update

**Comment by ToxicLand** [comment] 2022-04-07 00:07
Same issue here

**Comment by addaleax** [comment] 2022-04-07 13:48
@ToxicLand @abdudsoul Can you share screenshots of what exactly you are doing? In particular, the error message and the before/after state in the JSON viewer?

**Comment by ToxicLand** [comment] 2022-04-08 01:43
@addaleax Sure. This first image shows that in the default view, _id type is Int64. https://i.imgur.com/uVVdUqV.jpg
The second one shows the value of region, this is what I'm going to change to something different, using the json editor view (any change will trigger the bug) https://i.imgur.com/lYJqoZD.jpg
The third image shows that the type of _id has changed to Int32. This causes problems with my application. https://i.imgur.com/mUTsyIK.jpg
The last image shows the error I get when I try to change it back to Int64. https://i.imgur.com/pA8X8GA.jpg
Only way to fix this is to downgrade Compass and then change it manually.

**Comment by addaleax** [comment] 2022-04-08 13:07
Thank you for bringing this up! I’ve opened https://jira.mongodb.org/browse/COMPASS-5711 (and the related, also regressed https://jira.mongodb.org/browse/COMPASS-5710) to track this.

**Comment by addaleax** [comment] 2022-04-12 15:17
This should be fixed in the next release, thanks for reporting!

**Closed by addaleax** 2022-04-12 15:17 UTC

**Comment by ToxicLand** [comment] 2022-04-15 11:33
@addaleax I just installed the latest release that fixed the type changing itself upon modifying the document, but if I want to change existing (affected by the bug) documents from Int32 to Int64 using the default view, I still get a "Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id'".  Currently the workaround for this is to switch to the json editor, and apply "_id": {"$numberLong": "3"}.

**Comment by addaleax** [comment] 2022-04-19 11:40
@ToxicLand Yeah, that is honestly kind of expected, even if it might not be obvious why :confused: The table and “normal” document view use [`findOneAndUpdate`](https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndUpdate/) for changing a document, where `_id` is really immutable. Due to the way the JSON view/editing works, we can’t (easily) do the same there, we use [`findOneAndReplace`](https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndReplace/) instead. 

This does come with concrete downsides – for example, if the document was changed by something else in the background, this will still replace the entire document with whatever was in the JSON editor, rather than accounting for those other updates. The other editing modes don’t have this issue. I’ve opened https://jira.mongodb.org/browse/COMPASS-5753 for us to talk about this a bit further, but I can’t promise that we’ll make any changes here per se.

**Comment by Elyaegard** [comment] 2023-07-28 21:03
Hey abdu
Iam elyar
abdu update when come?
