### ISSUE TITLE
[v1.24.1] Can not connect DB

### ISSUE THREAD

**Issue by abel3t** [mongodb-js/compass#2075] opened 2020-12-14 05:29 UTC
- I have cluster mongodb and it can access with openVPN. 
- I use connection string `mongodb://<username>:<password>@<host>:<port>/<db>?authSource=admin`.
- I can connect to my db with Compass v1.22.1.
Please help me! Thanks!

**Comment by Anemy** [comment] 2020-12-14 16:06
Hi @abel3t we've been able to reproduce this issue. Looks like the new version of the node mongodb driver handles direct connections slightly differently than we're used to. We're working on a fix. For now I'd recommend using a pre 1.24.1 version :/
Tracking in https://jira.mongodb.org/secure/RapidBoard.jspa?rapidView=1185&view=detail&selectedIssue=COMPASS-4534 
Thanks for reporting!

**Comment by Anemy** [comment] 2020-12-14 18:47
Keeping this open till it's in Compass and released. I think github auto closed it.

**Comment by code-is-art** [comment] 2020-12-16 21:00
I can confirm that both 1.22.1 and 1.3.0 works for me when 1.24.1 does not using ssh tunnel.

**Comment by Anemy** [comment] 2020-12-17 15:10
@code-is-art @abel3t We've just released `1.24.6`. It's got the fix in it that should fix this issue. Going to close this, please reopen if you update and still find the connection not working.
Thanks again for posting the issue! If y'all ever think of some cool things we can add to improve Compass feel free to add it to our feature request forum - or upvote if it's already there: https://feedback.mongodb.com/forums/924283-compass

**Closed by Anemy** 2020-12-17 15:10 UTC
